//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class variantGroup {
    
    private string namesField;
    
    private string displayNameField;
    
    private string gCardinalityField;
    
    private List<variant> variantField;
    
    /// <remarks/>
    public string names {
        get {
            return this.namesField;
        }
        set {
            this.namesField = value;
        }
    }
    
    /// <remarks/>
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string gCardinality {
        get {
            return this.gCardinalityField;
        }
        set {
            this.gCardinalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("variant")]
    public List<variant> variant {
        get {
            return this.variantField;
        }
        set {
            this.variantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class variant {

    private int indexField;

    private string namesField;
    
    private string displayNameField;
    
    private byte cardinalityField;

    private List<operation> manOperationsField;

    /// <remarks/>
    public int index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }

    /// <remarks/>
    public string names {
        get {
            return this.namesField;
        }
        set {
            this.namesField = value;
        }
    }
    
    /// <remarks/>
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public byte cardinality {
        get {
            return this.cardinalityField;
        }
        set {
            this.cardinalityField = value;
        }
    }

    /// <remarks/>
    public List<operation> manOperations
    {
        get
        {
            return this.manOperationsField;
        }
        set
        {
            this.manOperationsField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class operation
{

    private string namesField;

    private string displayNameField;

    private List<string> preconditionField;

    private List<string> postconditionField;

    /// <remarks/>
    public string names
    {
        get
        {
            return this.namesField;
        }
        set
        {
            this.namesField = value;
        }
    }

    /// <remarks/>
    public string displayName
    {
        get
        {
            return this.displayNameField;
        }
        set
        {
            this.displayNameField = value;
        }
    }

    /// <remarks/>
    public List<string> precondition
    {
        get
        {
            return this.preconditionField;
        }
        set
        {
            this.preconditionField = value;
        }
    }

    /// <remarks/>
    public List<string> postcondition
    {
        get
        {
            return this.postconditionField;
        }
        set
        {
            this.postconditionField = value;
        }
    }

}
